merge: 1.1.2
commit a5fd7960a5260c4ee7df2d11f19bcf672aa077f1
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Tue Apr 11 11:53:11 2023 -0400

    feat: Add SetupBuffer in Renderer

    Put in Namespace the renderer to avoid collision with other class

commit 7b8f0922790801682d0888734ddfd5fa18f97b7e
Merge: 74ac2bb d801882
Author: Angel-2180 <a.gimer@student.isartdigital.com>
Date:   Sat Apr 8 13:42:39 2023 -0400

    merge: material & texture in RHI

    refactor material& texture code to use rhi

commit d801882585d3bf76680dfa305f859178c11a158a
Author: Ross <a.goes@student.isartdigital.com>
Date:   Thu Apr 6 14:07:54 2023 -0400

    refactor: Skybox & coding norme

commit 74ac2bba63f33f6e97aa747d127c256c0c8f99c3
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Wed Apr 5 12:01:38 2023 -0400

    refactor: Update some parameter name

commit 66ac65bb336901a6d2d59634d871046163b4dc3e
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Wed Apr 5 11:39:43 2023 -0400

    feat: Add RHI backbone to project

commit f9da1d99571c56cccd6a12478ef720d6d92e73dd
Author: Ross <a.goes@student.isartdigital.com>
Date:   Tue Apr 4 23:32:01 2023 -0400

    feat: add skybox

commit 4dcbee8af344dbb2b08e7e8e0203b055aa13b60d
Merge: afc8689 33935dd
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Tue Apr 4 15:03:04 2023 -0400

    merge: Add Multithread to dev

    Reviewed by Kouros

commit 33935dd15ca9ffdf8c69ac44c63ddcc29dda0bd6
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Tue Apr 4 14:08:57 2023 -0400

    feat: Add Multithread Resources

    Add 'Q' and 'E' key for mouvement of camera to go up and down

commit edcd51cf12ca7c0a9b3f596e00cb31f54c943eb2
Author: Ross <a.goes@student.isartdigital.com>
Date:   Tue Apr 4 13:32:48 2023 -0400

    waiting for review

commit afc8689981bcfb682a45e7e6679371baa888d9b2
Author: Kouros LOTFI <k.lotfi@student.isartdigital.com>
Date:   Tue Apr 4 09:00:40 2023 -0500

    fix: Scripts were not cloned

commit 878f8ac9cd958a8e3bc346936d91e9b7a343ddd9
Author: Kouros LOTFI <k.lotfi@student.isartdigital.com>
Date:   Tue Apr 4 08:37:56 2023 -0500

    fix: fixed abstract class error after merge

commit 4d717dd4c73a2ab5728d9f40f09cf66853001db4
Merge: 8cc08f0 57ceb18
Author: Kouros LOTFI <k.lotfi@student.isartdigital.com>
Date:   Tue Apr 4 08:28:03 2023 -0500

    Merge branch 'dev' of ssh://git.isartintra.com:2424/2022/Moteur_GPM2025/Mojitos into dev

commit 8cc08f02b36ea4113b21b7d680e427e7062dcbd0
Author: Kouros LOTFI <k.lotfi@student.isartdigital.com>
Date:   Tue Apr 4 08:27:47 2023 -0500

    chore: missing files

commit f533f7bdbb42b9cdc05a2b6c3a345eb1bec07f75
Merge: b6cb29a 64c66fd
Author: Kouros LOTFI <k.lotfi@student.isartdigital.com>
Date:   Tue Apr 4 08:26:22 2023 -0500

    merge StartAwakeLateUpdate into dev

commit 376aa0fb647223394c7ef61db8f3180468e87e7a
Author: AymericIsart <a.goes@student.isartdigital.com>
Date:   Mon Apr 3 11:58:01 2023 -0400

    refactor : Modification of Model and Shader for materials

commit ab1524a67d56e07e54de8bbe789358db4f1da8cc
Author: AymericIsart <a.goes@student.isartdigital.com>
Date:   Mon Apr 3 11:54:12 2023 -0400

    refactor : Add materials and models class

    Yet to finish those class

commit 5403ae0e1da6d6af2ee925bf25465b3cdf3b6ead
Author: AymericIsart <a.goes@student.isartdigital.com>
Date:   Mon Apr 3 11:26:31 2023 -0400

    feat: Add Texture class

commit 57ceb18f48f3c80b39c453df637910c77470a91f
Merge: fb9fa8d b6cb29a
Author: Angel-2180 <a.gimer@student.isartdigital.com>
Date:   Mon Apr 3 22:19:16 2023 -0400

    merge: Add copy of game object

commit fb9fa8d03e1320f2891f0041af4a9783e143e943
Author: Angel-2180 <a.gimer@student.isartdigital.com>
Date:   Mon Apr 3 22:16:10 2023 -0400

    refactor: Use of Assimp statically

commit b6cb29a17d2a1292900347341167c00c5c281900
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Mon Apr 3 11:03:19 2023 -0400

    feat: Add rule of 5 for GameObject

    add also necessaries constructor for all components as well

commit 64c66fd5f9bb06d85514f448e7dfc9fa0d0fe0c0
Author: Kouros26 <kouroslf@gmail.com>
Date:   Sat Mar 11 13:57:21 2023 -0500

    feat: Additionnal script functions working

commit f9a5a4f47e5b0e4c3f984232b99b7af6e6d813d9
Merge: 12498a3 441faf5
Author: Kouros26 <kouroslf@gmail.com>
Date:   Fri Mar 10 15:57:31 2023 -0500

    merge

commit 12498a3f7e028ae9b7c06e7af950e85f6a9bd898
Merge: c8bba5d 268b759
Author: Kouros26 <kouroslf@gmail.com>
Date:   Fri Mar 10 15:56:37 2023 -0500

    merge: SceneGraph, reviewed by Aymeric

commit 441faf5cbd5ffe2c9a816142539393406aa7cfc9
Author: Ross <a.goes@student.isartdigital.com>
Date:   Fri Mar 10 15:34:56 2023 -0500

    add unreal basics model

commit 268b75981f2c66cacfafa16a778fd0ab8dd14c37
Author: Kouros26 <kouroslf@gmail.com>
Date:   Fri Mar 10 15:09:54 2023 -0500

    feat: SceneGraph working

commit 393eaba62294490213d8121b7b44c41fa325ef12
Merge: 3c565cc 76d6a50
Author: Kouros26 <kouroslf@gmail.com>
Date:   Fri Mar 10 15:08:40 2023 -0500

    merge

commit 3c565cc0464e95e355466fb1c236bcfd3eb2085a
Author: Kouros26 <kouroslf@gmail.com>
Date:   Fri Mar 10 15:04:51 2023 -0500

    feat: SceneGraph working

commit c8bba5d22379636cc99f2b12c8703c69065a19b1
Author: Angel-2180 <a.gimer@student.isartdigital.com>
Date:   Fri Mar 10 14:59:17 2023 -0500

    refactor: Remove Spotlight Usage

commit b48a83a80fdff114052d402add1c332b10d28555
Merge: e2a4c70 1ae7dee
Author: Angel-2180 <a.gimer@student.isartdigital.com>
Date:   Fri Mar 10 14:56:56 2023 -0500

    merge: TransformWithQuat into dev

    Reviewed by kouros and Aymeric

commit e2a4c7044888ba1b7dd07040f6a6304648755af0
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Fri Mar 10 12:09:01 2023 -0500

    refactor: Try to fix problem with Light

commit 23cace8ffbbe487ee5d75789ca9f520650c7212b
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Fri Mar 10 11:46:12 2023 -0500

    docs: Add Documentation to project

commit 76d6a5086d3f92a0e4cd73fda8bb8e490c7bbc1e
Author: Kouros LOTFI <k.lotfi@student.isartdigital.com>
Date:   Thu Mar 9 16:00:13 2023 -0500

    refactor: Add parent/child system for transform

commit 06c1f3668fa769f09434528d92b9f391476f2011
Author: Kouros LOTFI <k.lotfi@student.isartdigital.com>
Date:   Thu Mar 9 16:00:13 2023 -0500

    Progress made

commit 1ae7dee3c628ec385d8c80ec153a0d3b373882e2
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Thu Mar 9 15:49:21 2023 -0500

    refactor: Remove block of orientation of camera

commit b4507c95fd226d486117a52ab23a2126b78514b4
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Thu Mar 9 11:31:03 2023 -0500

    refactor: Update opengl 3.3 to 4.6

commit 914c2d5612f35e9ae6ee410b3d064ba442e67c3f
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Thu Mar 9 10:34:21 2023 -0500

    fix: Resolve all problem from Rotation of Camera

commit f30225b76f4cd2997cede375ba9141632d4a60e1
Author: Angel-2180 <a.gimer@student.isartdigital.com>
Date:   Wed Mar 8 17:10:16 2023 -0500

    refactor: try to fix cmaera rot using quat

commit 709d3458b9a56c159765ccf5376cba3b3815f972
Author: Ross <a.goes@student.isartdigital.com>
Date:   Wed Mar 8 16:32:37 2023 -0500

    Editor camera was reversed ?

commit 616fc735c1bab14f81171e8c9b7952c1186835c2
Merge: 7012b4f f0a31e0
Author: Ross <a.goes@student.isartdigital.com>
Date:   Wed Mar 8 16:29:00 2023 -0500

    Merge branch 'Lights' into dev

commit f0a31e0a39a9e0024af2f4842026a595d9df9d84
Merge: 85f09b3 d002e43
Author: Ross <a.goes@student.isartdigital.com>
Date:   Wed Mar 8 16:28:40 2023 -0500

    merge?

commit 85f09b3308bf060302c41544dfcae5877cb20c3c
Author: Ross <a.goes@student.isartdigital.com>
Date:   Wed Mar 8 16:27:24 2023 -0500

    code reviewed by kouros and angel

commit 303659a2217ebf70e2f64996a782068769dc150a
Author: Angel-2180 <a.gimer@student.isartdigital.com>
Date:   Wed Mar 8 16:08:44 2023 -0500

    refactor: Use right up and forward of cam

commit 75f98f95b71bf189a8895ba1363a59cb536dd203
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Tue Mar 7 16:04:47 2023 -0500

    refactor: Use Up and Right of camera

    for rotation

commit d002e43daad607131b72f75288d20dcc3c964bef
Author: Ross <a.goes@student.isartdigital.com>
Date:   Mon Mar 6 23:57:19 2023 -0500

    refactor: Wrap GameObjects in GameObjectManager

commit 98012f636dcbbd22a55d10ab0e7d5cf181bc875c
Author: Ross <a.goes@student.isartdigital.com>
Date:   Mon Mar 6 23:19:26 2023 -0500

    refactor: Components in GameObject

commit ae21d7ad629ade24771c2dccf7aad3d11a9324f5
Author: Ross <a.goes@student.isartdigital.com>
Date:   Mon Mar 6 23:13:50 2023 -0500

    refactor: Remove FixedQueue

commit 87ba4cacd239f35e8a76dafa38e1de41a846f7d3
Author: Ross <a.goes@student.isartdigital.com>
Date:   Mon Mar 6 23:57:19 2023 -0500

    wrap GameObjects in GameObjectManager

commit f279c079be0c2b6dbdb91c11eaafd8484347349f
Author: Ross <a.goes@student.isartdigital.com>
Date:   Mon Mar 6 23:19:26 2023 -0500

    wrap components in GameObject

commit 9651a9f0abcb10d7321c0669a4bff04b360a5651
Author: Ross <a.goes@student.isartdigital.com>
Date:   Mon Mar 6 23:13:50 2023 -0500

    remove fixedQueue

commit c805a8f4bbbd991f1e65acc96c78ff10866f0a2a
Author: Ross <a.goes@student.isartdigital.com>
Date:   Mon Mar 6 17:57:26 2023 -0500

    feat: light no review

commit 469ccc9ae4dc43fd31b9a78277cf859b013067df
Author: Ross <a.goes@student.isartdigital.com>
Date:   Sun Mar 5 14:07:16 2023 -0500

    feat: Lights fix, (error on pointlight now fixed)

commit 18913803f2d02d6e0607570b3b66c5a37f1eb667
Author: Angel-2180 <a.gimer@student.isartdigital.com>
Date:   Sat Mar 4 21:07:22 2023 -0500

    fix: Add UnUse of Shader

    to avoid mixup between shaders added unuse function to shaders

commit 49da675ceb078ca67fd8998210a56671b523376a
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Fri Mar 3 17:00:27 2023 -0500

    refactor: Try to use Quaternion for Transform

    Issues with Rotation of camera

commit a0c1158f0cc0114bda6fe5a7031e54277666f204
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Wed Mar 1 14:08:37 2023 -0500

    feat: Add Test for FromEuler function

commit 2f5286d0efdb039e104c8740194715648a778be2
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Wed Mar 1 14:08:09 2023 -0500

    feat: Change rotation to use Quaternions

    Change FVec3 Rotation to FQuat Rotation //Fix some weird rotation with camera

commit 321219bcfa2ba8aa4b9888e0cc70b5261e90f3ae
Author: Ross <a.goes@student.isartdigital.com>
Date:   Tue Feb 28 18:30:19 2023 -0500

    feat: Dirlight are working

commit 7d4c7648bad1cb9b6f70c097fd2ba26c67af574f
Author: AymericIsart <a.goes@student.isartdigital.com>
Date:   Tue Feb 28 16:45:33 2023 -0500

    feat: Lights + some tiny fixes in various scripts

commit 7012b4f3281fa0fc396c79a4037aad329b83312d
Merge: 5e0b405 d9fc76e
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Tue Feb 28 15:08:49 2023 -0500

    merge: Reviewed by Kouros & Aymeric

commit 5e0b405e102725b9bf2e3ec7a15a9adcddf68fec
Author: Kouros26 <kouroslf@gmail.com>
Date:   Tue Feb 28 14:58:03 2023 -0500

    perf: Added missing refs, consts, and minor optimizations

commit d9fc76e0a99b1c70be8d8d7d57a87494abb5e46e
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Tue Feb 28 12:03:27 2023 -0500

    refactor: Change order of glm:quat on one test

    change the order to avoid error of calcul

commit 6e7ef2af8157bc3f372d1a06a469d7fce0609d55
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Tue Feb 28 12:02:46 2023 -0500

    feat: Add UnitTest for Transform

    UnitTest for transform that use quat as rotation

commit fcf2a9be936266b4b9cbb64a215399128b90fcd0
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Tue Feb 28 12:02:14 2023 -0500

    fix: Change code to remove warning

commit 9ff2a7c507955ac6a6515aad52924387cd6f0c0b
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Tue Feb 28 12:01:43 2023 -0500

    perf: Change Cmake of LibMaths to use WX flag of compilation

commit 70e9af037c36b7e5296cb3623fdef3d358654fcd
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Tue Feb 28 12:01:07 2023 -0500

    perf: Change Cmake to use master branch for LibMath

commit da7d2e91dd37131527b714e287f714e5b861a6e6
Author: AymericIsart <a.goes@student.isartdigital.com>
Date:   Tue Feb 28 11:20:37 2023 -0500

    Reviewed by Angel

commit 263463e829137440b59c1972be4860672b697b24
Author: AymericIsart <a.goes@student.isartdigital.com>
Date:   Tue Feb 28 11:19:37 2023 -0500

    feat : Better editor Camera + Draw Guizmos

commit 88a1288e2066c960d06197a095f07cf068635caf
Author: Angel-2180 <a.gimer@student.isartdigital.com>
Date:   Mon Feb 27 22:44:45 2023 -0500

    refactor: Active all Test

commit d2c3f4153afedba1f0b18aba3df8c1665921ab5d
Author: Angel-2180 <a.gimer@student.isartdigital.com>
Date:   Mon Feb 27 22:44:17 2023 -0500

    feat: Add UnitTest for FQuat

commit 7f150db8a77d5fb83de37a82ca79f9d6c80c1adb
Author: Angel-2180 <a.gimer@student.isartdigital.com>
Date:   Mon Feb 27 22:43:56 2023 -0500

    refactor: Update some Test

    Rotation for Euler and Transform Test

commit e15c96d9aed589a8094ecfd29bda83d0519a2692
Author: Ross <a.goes@student.isartdigital.com>
Date:   Mon Feb 27 16:38:53 2023 -0500

    feat: Better editor camera + try fix getfront, up and right on Transfrom + add Draw Guizmos

commit 8d4f4c76a99537834150d941e7ba40d0ff9173be
Author: Ross <a.goes@student.isartdigital.com>
Date:   Sun Feb 26 15:25:13 2023 -0500

    feat: editor camera with mouse wheel

commit a8fac9a06032407f40e9542cb6d84e7177a7ca51
Author: Angel-2180 <a.gimer@student.isartdigital.com>
Date:   Sun Feb 26 14:59:37 2023 -0500

    refactor: Change Cmake

    change CMake to Use Debug branch of the LibMaths, better to avoid conflict

commit 689a4eb6697e05481916af2c4cfe794c43ebd54b
Author: Angel-2180 <a.gimer@student.isartdigital.com>
Date:   Sun Feb 26 14:53:20 2023 -0500

    feat: Add Mat4 UnitTest

commit 174cdd5e6403721599687117ed31742695403c0e
Author: Angel-2180 <a.gimer@student.isartdigital.com>
Date:   Sun Feb 26 14:53:08 2023 -0500

    feat: Add Mat3 Unit Test

commit 106bfb544a088ff9debcc96c0ae6cbf76a7d53bd
Author: Ross <a.goes@student.isartdigital.com>
Date:   Sat Feb 25 16:41:43 2023 -0500

    merge: Reviewed by Kouros and Angel

commit b13baae55230c8ec07176205e8bb3ce144437ac2
Author: Ross <a.goes@student.isartdigital.com>
Date:   Sat Feb 25 16:39:54 2023 -0500

    feat: Draw lines

commit 3c97973ca8303d47c02912e1eccabff2fb5eaa6b
Author: Ross <a.goes@student.isartdigital.com>
Date:   Sat Feb 25 16:30:31 2023 -0500

    feat: draw lines

commit fe2f0eea17b8712801fa6c503e238e33cdeb68de
Merge: b052b22 4246d6d
Author: Ross <a.goes@student.isartdigital.com>
Date:   Sat Feb 25 15:19:02 2023 -0500

    merge with resource manager

commit b052b22106252e598a4aaa2a6d4eb7ad72b6f9de
Author: Ross <a.goes@student.isartdigital.com>
Date:   Sat Feb 25 15:15:14 2023 -0500

    perf: Resource manager upgraded

commit 1ce55a51f8d4f7794ecc5fea023e953f296746b4
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Fri Feb 24 13:34:37 2023 -0500

    feat: Add more UnitTest

commit ad48a3eed466c8a0f9a6565d5fae35e09c04f953
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Fri Feb 24 11:35:54 2023 -0500

    feat: Add Vec2 UnitTest

commit 48b0cc273aa80b8245e954a58e0ca0a859270240
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Fri Feb 24 11:35:40 2023 -0500

    feat: Add all already made unitTest

commit cd02b37665bcd8dde65ad79ea644a3714eddb891
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Fri Feb 24 11:35:15 2023 -0500

    feat: Add UnitTest project

commit 04d03e4d14b83bf4fbf1d043a2e81d8c714ddea9
Author: Ross <a.goes@student.isartdigital.com>
Date:   Thu Feb 23 16:38:14 2023 -0500

    add Resourcemanager + model became a resource + gameObject can only have one model

commit 4246d6d9a3896c509ff7a6e51a15e24f47723fda
Merge: b509271 788804a
Author: Kouros26 <kouroslf@gmail.com>
Date:   Thu Feb 23 14:19:25 2023 -0500

    Merge branch 'dev' of ssh://git.isartintra.com:2424/2022/Moteur_GPM2025/Mojitos into dev

commit b5092716db58d02beee075fa50b1234ddee163ff
Author: Kouros26 <kouroslf@gmail.com>
Date:   Thu Feb 23 14:18:41 2023 -0500

    fix: version major and minor put in a class

commit 40004062629eedb692f8743189877e9e87823285
Author: Kouros26 <kouroslf@gmail.com>
Date:   Thu Feb 23 13:27:32 2023 -0500

    fix: removed useless code

commit 08f33811eb20fec85f8d20aaf3ac3946bd0cdbab
Author: Kouros26 <kouroslf@gmail.com>
Date:   Thu Feb 23 13:21:16 2023 -0500

    feat: VSync implemented

commit 4294b6e86f36a8b80dd7a6b7f26976c04d500957
Author: Ross <a.goes@student.isartdigital.com>
Date:   Thu Feb 23 13:14:11 2023 -0500

    create new branch

commit 788804a9fe2891e82a59b0d9119b643649260a34
Author: Angel-2180 <a.gimer@student.isartdigital.com>
Date:   Thu Feb 23 01:15:28 2023 -0500

    chore: Change integration of ImGui in cmake

commit d26895f86d21fc6ae2efd34405afa8c9f93b9425
Author: Kouros26 <kouroslf@gmail.com>
Date:   Wed Feb 22 21:33:42 2023 -0500

    feat: ImGUI integration + Editor Interface logic

commit 619ee3be10d2b92083c9bd26b72b38eec211871a
Author: AymericIsart <a.goes@student.isartdigital.com>
Date:   Wed Feb 22 11:53:02 2023 -0500

    code review

commit ad58449e96a7126b1aafb029cfd4fb954e1a18e6
Author: AymericIsart <a.goes@student.isartdigital.com>
Date:   Wed Feb 22 11:41:44 2023 -0500

    load assimp finished

commit 5b848d8a4965847bbf02879070b915c019a22cc4
Merge: 111e75e 1e71c37
Author: AymericIsart <a.goes@student.isartdigital.com>
Date:   Wed Feb 22 10:45:41 2023 -0500

    Merge branch 'assimpLoad' of ssh://git.isartintra.com:2424/2022/Moteur_GPM2025/Mojitos into assimpLoad

commit 111e75e169fa432839e25bb1c0aa2269d6ccd305
Author: AymericIsart <a.goes@student.isartdigital.com>
Date:   Wed Feb 22 10:45:32 2023 -0500

    add shaders

commit 1e71c37cc4aa9f83f3a671a3ec8c97fed4804b9d
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Wed Feb 22 10:42:58 2023 -0500

    fix: Link Problem

commit 0c087612267e9ed046795b8304636371a7413b7c
Author: Ross <a.goes@student.isartdigital.com>
Date:   Tue Feb 21 22:24:48 2023 -0500

    add my files, error on assimp library

commit 45bb5dfe704147bc53f5c6cb0ed7c4700ec08f6e
Merge: 41c58c9 30d6561
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Tue Feb 21 16:03:16 2023 -0500

    Merge branch 'bugFix' into dev

commit 30d6561fff6200b4755b0005fa5018c8abc0a9c0
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Tue Feb 21 16:01:34 2023 -0500

    fix: Link error to GLFW

commit 41c58c9a7a824a6e9908d0465d1f8dff39e3ded5
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Tue Feb 21 15:10:01 2023 -0500

    chore: Add Warning as Error for MSVC

commit d5c4f416ba6ae8ac3a8a991ef2e33c7b202f3ece
Author: Kouros26 <kouroslf@gmail.com>
Date:   Tue Feb 21 15:08:00 2023 -0500

    Bug : GLFW Unresolved external symbols

commit 67ce0a43f64955ea3be2534000f75ba755411f81
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Tue Feb 21 13:29:23 2023 -0500

    fix: Add missing folders

commit 4ed4f6806238f8b569ba4de9dd0a14c61025b2d5
Author: Angel <a.gimer@student.isartdigital.com>
Date:   Tue Feb 21 13:16:14 2023 -0500

    feat: Add basic Architecture of project